import { Service, Vendor } from "../types/vendor";
export const vendorServicesListStatic: Service[] = [
  {
    id: "1",
    title: "Spa Treatments - Pet Grooming",
    description: "Luxurious spa treatments for your beloved pets.",
    category: "Pet Grooming",
    subcategory: "Spa Treatments",
    includes: ["Bath", "Massage", "Brushing"],
    priceRange: { min: 50, max: 100 },
    performers: [],
    discount: 40,
    durationMin: 60,
  },
  {
    id: "2",
    title: "Dental Care - Pet Grooming",
    description: "Professional dental care services for pets.",
    category: "Pet Grooming",
    subcategory: "Dental Care",
    includes: ["Teeth Cleaning", "Oral Examination"],
    priceRange: { min: 80, max: 150 },
    performers: [],
    durationMin: 45,
  },
  // Veterinary Care
  {
    id: "3",
    title: "Vaccinations - Veterinary Care",
    description: "Essential vaccinations for your pets.",
    category: "Veterinary Care",
    subcategory: "Vaccinations",
    includes: ["General Check-up", "Vaccination Shots"],
    priceRange: { min: 30, max: 80 },
    performers: [],
    durationMin: 30,
  },
  {
    id: "4",
    title: "Routine Check-ups - Veterinary Care",
    description: "Regular check-ups to ensure your pet's well-being.",
    category: "Veterinary Care",
    subcategory: "Routine Check-ups",
    includes: ["Physical Examination", "Parasite Screening"],
    priceRange: { min: 50, max: 100 },
    performers: [],
    durationMin: 45,
  },
  // Pet Supplies
  {
    id: "5",
    title: "Pet Food - Pet Supplies",
    description: "High-quality pet food for optimal nutrition.",
    category: "Pet Supplies",
    subcategory: "Pet Food",
    includes: ["Dry Food", "Canned Food", "Treats"],
    priceRange: { min: 10, max: 50 },
    performers: [],
    durationMin: 0,
  },
  {
    id: "6",
    title: "Toys - Pet Supplies",
    description: "Fun toys to keep your pet entertained.",
    category: "Pet Supplies",
    subcategory: "Toys",
    includes: ["Chew Toys", "Interactive Toys"],
    priceRange: { min: 5, max: 30 },
    performers: [],
    durationMin: 0,
  },
  {
    id: "7",
    title: "Overnight Stays - Pet Boarding",
    description: "Comfortable overnight stays for your pets.",
    category: "Pet Boarding",
    subcategory: "Overnight Stays",
    includes: ["Private Room", "Regular Exercise"],
    priceRange: { min: 30, max: 80 },
    performers: [],
    durationMin: 12 * 60, // 12 hours
  },
  {
    id: "8",
    title: "Daycare - Pet Boarding",
    description: "Safe and engaging daycare services for pets.",
    category: "Pet Boarding",
    subcategory: "Daycare",
    includes: ["Supervised Playtime", "Socialization"],
    priceRange: { min: 20, max: 50 },
    performers: [],
    durationMin: 8 * 60, // 8 hours
  },
  // Pet Training
  {
    id: "9",
    title: "Obedience Training - Pet Training",
    description: "Effective obedience training to improve your pet's behavior.",
    category: "Pet Training",
    subcategory: "Obedience Training",
    includes: ["Basic Commands", "Leash Training"],
    priceRange: { min: 60, max: 120 },
    performers: [],
    durationMin: 60,
  },
  {
    id: "10",
    title: "Puppy Training - Pet Training",
    description: "Specialized training tailored for young puppies.",
    category: "Pet Training",
    subcategory: "Puppy Training",
    includes: ["Potty Training", "Socialization"],
    priceRange: { min: 70, max: 130 },
    performers: [],
    durationMin: 60,
  },
];

export const vendorListStatic: Vendor[] = [
  {
    id: 1,
    name: "Vendor 1",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus id error repudiandae vitae minima, qui nostrum accusantium facere sunt fuga.",
    address: {
      city: "City 1",
      postalCode: "12345",
      street: "Street 1",
      houseNumber: "1",
      apartmentNumber: "A",
    },
    email: "vendor1@email.com",
    phoneNumber: "1234567890",
    location: "Location 1",
    openingHours: [
      {
        day: "monday",
        open: "9:00",
        close: "15:00",
      },
      {
        day: "tuesday",
        open: "9:00",
        close: "15:00",
      },
      {
        day: "wednesday",
        open: "9:00",
        close: "15:00",
      },
      { day: "thursday", open: "9:00", close: "15:00" },
      {
        day: "friday",
        open: "9:00",
        close: "15:00",
      },
      { day: "saturday", closed: true },
      { day: "sunday", closed: true },
    ],
    services: vendorServicesListStatic,
    reviews: [],
  },
  {
    id: 2,
    name: "Vendor 2",
    email: "vendor1@emai2.com",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos itaque, expedita vero soluta inventore alias assumenda quidem suscipit quas iure deleniti quisquam fuga autem voluptatum eaque velit ab incidunt aperiam? Rerum necessitatibus quo obcaecati sed vitae exercitationem? Ullam, numquam ratione.",
    address: {
      city: "City 2",
      postalCode: "23456",
      street: "Street 2",
      houseNumber: "2",
      apartmentNumber: "B",
    },
    phoneNumber: "2345678901",
    location: "Location 2",
    openingHours: [
      {
        day: "monday",
        open: "10:00",
        close: "16:00",
      },
      {
        day: "tuesday",
        open: "10:00",
        close: "16:00",
      },
      {
        day: "wednesday",
        open: "10:00",
        close: "16:00",
      },
      { day: "thursday", open: "10:00", close: "16:00" },
      {
        day: "friday",
        open: "10:00",
        close: "16:00",
      },
      { day: "saturday", open: "10:00", close: "16:00" },
      { day: "sunday", open: "10:00", close: "16:00" },
    ],
    services: vendorServicesListStatic,
    reviews: [],
  },
  {
    id: 3,
    name: "Vendor 3",
    email: "vendor3@email.com",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex consequatur doloremque temporibus repellendus aliquam minus error earum, quidem iste numquam.",
    address: {
      city: "City 3",
      postalCode: "34567",
      street: "Street 3",
      houseNumber: "3",
      apartmentNumber: "C",
    },
    phoneNumber: "3456789012",
    location: "Location 3",
    openingHours: [
      {
        day: "monday",
        open: "11:00",
        close: "17:00",
      },
      {
        day: "tuesday",
        open: "11:00",
        close: "17:00",
      },
      {
        day: "wednesday",
        open: "11:00",
        close: "17:00",
      },
      { day: "thursday", open: "11:00", close: "17:00" },
      {
        day: "friday",
        open: "11:00",
        close: "17:00",
      },
      { day: "saturday", open: "11:00", close: "17:00" },
      { day: "sunday", open: "11:00", close: "17:00" },
    ],
    services: vendorServicesListStatic,
    reviews: [],
  },
  {
    id: 4,
    email: "vendor4@email.com",
    name: "Vendor 4",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium animi aliquid debitis ratione praesentium alias doloribus dolorum a labore veritatis!",
    address: {
      city: "City 4",
      postalCode: "45678",
      street: "Street 4",
      houseNumber: "4",
      apartmentNumber: "D",
    },
    phoneNumber: "4567890123",
    location: "Location 4",
    openingHours: [
      {
        day: "monday",
        open: "112:00",
        close: "18:00",
      },
      {
        day: "tuesday",
        open: "112:00",
        close: "18:00",
      },
      {
        day: "wednesday",
        open: "112:00",
        close: "18:00",
      },
      { day: "thursday", open: "112:00", close: "18:00" },
      {
        day: "friday",
        open: "112:00",
        close: "18:00",
      },
      { day: "saturday", open: "112:00", close: "18:00" },
      { day: "sunday", open: "112:00", close: "18:00" },
    ],
    services: vendorServicesListStatic,
    reviews: [],
  },
  {
    id: 5,
    email: "vendor5@email.com",
    name: "Vendor 5",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium animi aliquid debitis ratione praesentium alias doloribus dolorum a labore veritatis!",
    address: {
      city: "City 5",
      postalCode: "56789",
      street: "Street 5",
      houseNumber: "5",
      apartmentNumber: "E",
    },
    phoneNumber: "5678901234",
    location: "Location 5",
    openingHours: [
      {
        day: "monday",
        open: "11:00",
        close: "19:00",
      },
      {
        day: "tuesday",
        open: "11:00",
        close: "19:00",
      },
      {
        day: "wednesday",
        open: "11:00",
        close: "19:00",
      },
      { day: "thursday", open: "11:00", close: "19:00" },
      {
        day: "friday",
        open: "11:00",
        close: "19:00",
      },
      { day: "saturday", open: "11:00", close: "19:00" },
      { day: "sunday", open: "11:00", close: "19:00" },
    ],
    services: vendorServicesListStatic,
    reviews: [],
  },
  {
    id: 6,
    email: "vendor6@email.com",
    name: "Vendor 6",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium animi aliquid debitis ratione praesentium alias doloribus dolorum a labore veritatis!",
    address: {
      city: "City 6",
      postalCode: "67890",
      street: "Street 6",
      houseNumber: "6",
      apartmentNumber: "F",
    },
    phoneNumber: "6789012345",
    location: "Location 6",
    openingHours: [
      {
        day: "monday",
        open: "12:00",
        close: "110:00",
      },
      {
        day: "tuesday",
        open: "12:00",
        close: "110:00",
      },
      {
        day: "wednesday",
        open: "12:00",
        close: "110:00",
      },
      { day: "thursday", open: "12:00", close: "110:00" },
      {
        day: "friday",
        open: "12:00",
        close: "110:00",
      },
      { day: "saturday", open: "12:00", close: "110:00" },
      { day: "sunday", open: "12:00", close: "110:00" },
    ],
    services: vendorServicesListStatic,
    reviews: [],
  },
  {
    id: 7,
    email: "vendor7@email.com",
    name: "Vendor 7",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium animi aliquid debitis ratione praesentium alias doloribus dolorum a labore veritatis!",
    address: {
      city: "City 7",
      postalCode: "78901",
      street: "Street 7",
      houseNumber: "7",
      apartmentNumber: "G",
    },
    phoneNumber: "7890123456",
    location: "Location 7",
    openingHours: [
      {
        day: "monday",
        open: "13:00",
        close: "111:00",
      },
      {
        day: "tuesday",
        open: "13:00",
        close: "111:00",
      },
      {
        day: "wednesday",
        open: "13:00",
        close: "111:00",
      },
      { day: "thursday", open: "13:00", close: "111:00" },
      {
        day: "friday",
        open: "13:00",
        close: "111:00",
      },
      { day: "saturday", open: "13:00", close: "111:00" },
      { day: "sunday", open: "13:00", close: "111:00" },
    ],
    services: vendorServicesListStatic,
    reviews: [],
  },
  {
    id: 8,
    email: "vendor8@email.com",
    name: "Vendor 8",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium animi aliquid debitis ratione praesentium alias doloribus dolorum a labore veritatis!",
    address: {
      city: "City 8",
      postalCode: "89012",
      street: "Street 8",
      houseNumber: "8",
      apartmentNumber: "H",
    },
    phoneNumber: "8901234567",
    location: "Location 8",
    openingHours: [
      {
        day: "monday",
        open: "14:00",
        close: "12:00",
      },
      {
        day: "tuesday",
        open: "14:00",
        close: "12:00",
      },
      {
        day: "wednesday",
        open: "14:00",
        close: "12:00",
      },
      { day: "thursday", open: "14:00", close: "12:00" },
      {
        day: "friday",
        open: "14:00",
        close: "12:00",
      },
      { day: "saturday", open: "14:00", close: "12:00" },
      { day: "sunday", open: "14:00", close: "12:00" },
    ],
    services: vendorServicesListStatic,
    reviews: [],
  },
  {
    id: 9,
    email: "vendor9@email.com",
    name: "Vendor 9",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium animi aliquid debitis ratione praesentium alias doloribus dolorum a labore veritatis!",
    address: {
      city: "City 9",
      postalCode: "90123",
      street: "Street 9",
      houseNumber: "9",
      apartmentNumber: "I",
    },
    phoneNumber: "9012345678",
    location: "Location 9",
    openingHours: [
      {
        day: "monday",
        open: "15:00",
        close: "1:00",
      },
      {
        day: "tuesday",
        open: "15:00",
        close: "1:00",
      },
      {
        day: "wednesday",
        open: "15:00",
        close: "1:00",
      },
      { day: "thursday", open: "15:00", close: "1:00" },
      {
        day: "friday",
        open: "15:00",
        close: "1:00",
      },
      { day: "saturday", open: "15:00", close: "1:00" },
      { day: "sunday", open: "15:00", close: "1:00" },
    ],
    services: vendorServicesListStatic,
    reviews: [],
  },
  {
    id: 10,
    email: "vendor10@email.com",
    name: "Vendor 10",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium animi aliquid debitis ratione praesentium alias doloribus dolorum a labore veritatis!",
    address: {
      city: "City 10",
      postalCode: "01234",
      street: "Street 10",
      houseNumber: "10",
      apartmentNumber: "J",
    },
    phoneNumber: "0123456789",
    location: "Location 10",
    openingHours: [
      {
        day: "monday",
        open: "16:00",
        close: "2:00",
      },
      {
        day: "tuesday",
        open: "16:00",
        close: "2:00",
      },
      {
        day: "wednesday",
        open: "16:00",
        close: "2:00",
      },
      { day: "thursday", open: "16:00", close: "2:00" },
      {
        day: "friday",
        open: "16:00",
        close: "2:00",
      },
      { day: "saturday", open: "16:00", close: "2:00" },
      { day: "sunday", open: "16:00", close: "2:00" },
    ],
    services: vendorServicesListStatic,
    reviews: [],
  },

  // Add more vendors here...
];
